spring:
  application:
    name: config-notification-server

  cloud:
    function:
      definition: "consumeNotification;consumeMessage"
    stream:
      bindings:
        consume-notification-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}config.update
        consume-message-in-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}config.message
logging:
  level:
    org.gridsuite.config.notification.server.notification-web-socket-handler: INFO
    org.gridsuite.config.notification.server.global-notification-web-socket-handler: INFO
