spring:
  application:
    name: config-notification-server

  profiles:
    active: default,local

  rabbitmq:
    addresses: rabbitmq
    port: 5672

  cloud:
    function:
      definition: consumeNotification
    stream:
      bindings:
        consumeNotification-in-0:
          destination: config.update

logging:
  level:
    org.gridsuite.config.notification.server.NotificationWebSocketHandler: INFO
